### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by juliaogris** [foxygoat/foxygo.at#2]
Consider setting up CI checks to verify that generated html files are "up-to-date" with lates jsonnet files.

Maybe there is also some jsonnet linting?

Consider automatically deploying changes merged into master probably via google cloudbuilds to make firbase access easier.

**Comment by juliaogris** [comment]
sorry :(

**Comment by juliaogris** [comment]
oh. not here anymore.

**Comment by camh-** [comment]
whoops, linked to the wrong issue in a commit and a PR. pity you can't clean up that mess
